import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { AppShell } from "@/components/app-shell";
import { WorkloadSettingsForm } from "@/components/workload-settings-form";
import { WeeklyManagementSummary } from "@/components/weekly-management-summary";
import { hasPermission } from "@/lib/permissions";
import { buildWeeklyManagementSummary, buildWorkspaceReport, minutesToHours, parseCompletionDateRange, reportRangeStart } from "@/lib/reporting";
import { listUserWorkspaces, requireWorkspaceBySlug } from "@/lib/server/authorization";
import { prisma } from "@/lib/server/prisma";

const statusLabels: Record<string, string> = { TODO: "To do", IN_PROGRESS: "In progress", DONE: "Completed", NO_ACTION_NEEDED: "No Action Needed" };
const REPORT_TASK_LIMIT = 5000;

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ workspace?: string; range?: string; completedFrom?: string; completedTo?: string }> }) {
  const session = await auth();
  if (!session?.user?.id || !session.user.email) redirect("/login");
  const query = await searchParams;
  const workspaces = await listUserWorkspaces(session.user.id);
  const slug = query.workspace || workspaces[0]?.slug;
  if (!slug) redirect("/login?error=no-workspace");
  const range = query.range === "all" || query.range === "90" ? query.range : "30";
  const completedFrom = query.completedFrom || "";
  const completedTo = query.completedTo || "";
  const customCompletionRange = parseCompletionDateRange(completedFrom, completedTo);
  const hasCustomCompletionRange = Boolean(completedFrom || completedTo);
  const { workspace, role, subject } = await requireWorkspaceBySlug(slug, { id: session.user.id, email: session.user.email });
  if (role !== "OWNER") redirect(`/board?workspace=${encodeURIComponent(slug)}`);
  const since = reportRangeStart(range);
  const outputDateFilter = "error" in customCompletionRange ? null : { not: null, ...(hasCustomCompletionRange ? { ...(customCompletionRange.start ? { gte: customCompletionRange.start } : {}), ...(customCompletionRange.end ? { lt: customCompletionRange.end } : {}) } : since ? { gte: since } : {}) };
  const reportTaskSelect = { id: true, title: true, status: true, priority: true, createdAt: true, updatedAt: true, startedAt: true, completedAt: true, dueAt: true, assigneeUserId: true, estimatedMinutes: true, remainingMinutes: true, actualMinutes: true, blockedAt: true, blockedReason: true, blockerTaskId: true, updatedProductsCount: true, newProductsCount: true, updatedImagesCount: true, newImagesCount: true } as const;
  const [tasks, outputTasks, summaryTasks, members] = await Promise.all([prisma.task.findMany({ where: { workspaceId: workspace.id, ...(since ? { createdAt: { gte: since } } : {}) }, select: reportTaskSelect, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: REPORT_TASK_LIMIT + 1 }), outputDateFilter ? prisma.task.findMany({ where: { workspaceId: workspace.id, completedAt: outputDateFilter }, select: reportTaskSelect, orderBy: [{ completedAt: "desc" }, { id: "desc" }], take: REPORT_TASK_LIMIT + 1 }) : Promise.resolve([]), prisma.task.findMany({ where: { workspaceId: workspace.id }, select: reportTaskSelect, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: REPORT_TASK_LIMIT + 1 }), prisma.workspaceMember.findMany({ where: { workspaceId: workspace.id }, select: { id: true, weeklyCapacityMinutes: true, availability: { where: { date: { gte: new Date(new Date().setUTCDate(new Date().getUTCDate() - 7)) } }, select: { date: true, availableMinutes: true } }, user: { select: { id: true, name: true, email: true } } } })]);
  const reportLimited = tasks.length > REPORT_TASK_LIMIT || outputTasks.length > REPORT_TASK_LIMIT || summaryTasks.length > REPORT_TASK_LIMIT;
  const reportTasks = tasks.slice(0, REPORT_TASK_LIMIT);
  const reportOutputTasks = outputTasks.slice(0, REPORT_TASK_LIMIT);
  const reportSummaryTasks = summaryTasks.slice(0, REPORT_TASK_LIMIT);
  const settings = { overloadThreshold: workspace.overloadThreshold, dueSoonDays: workspace.dueSoonDays, stalledAfterDays: workspace.stalledAfterDays };
  const report = buildWorkspaceReport(reportTasks, members, new Date(), reportOutputTasks, settings);
  const weeklySummary = buildWeeklyManagementSummary(reportSummaryTasks, members, new Date(), settings, report);
  const maxStatus = Math.max(...report.statuses.map((item) => item.count), 1);
  const maxPriority = Math.max(...report.priorities.map((item) => item.count), 1);
  const counts = report.productAndImageCounts;
  const countCards = [
    ["Updated products", counts.updatedProducts, "products"],
    ["New products", counts.newProducts, "products"],
    ["Updated images", counts.updatedImages, "images"],
    ["New images", counts.newImages, "images"],
  ] as const;
  const dateParams = new URLSearchParams({ workspace: slug, range });
  if (completedFrom) dateParams.set("completedFrom", completedFrom);
  if (completedTo) dateParams.set("completedTo", completedTo);
  const exportHref = `/api/reports?${dateParams.toString()}&format=csv`;
  const rangeHref = (value: string) => { const params = new URLSearchParams(dateParams); params.set("range", value); return `/reports?${params.toString()}`; };
  const today = new Date().toISOString().slice(0, 10);
  return <AppShell active="reports" userName={session.user.name} workspaces={workspaces} workspaceSlug={slug}>
    <header className="page-header"><div><span className="eyebrow">MANAGER COMMAND CENTER</span><h1>Team workload</h1><p>Balance capacity, resolve delivery risk, and improve the team’s flow of work.</p></div><a className="primary-button small export-link" href={exportHref}>Export CSV</a></header>
    <div className="report-period-label">Task health period</div><nav className="report-range" aria-label="Task health report period">{[["30", "30 days"], ["90", "90 days"], ["all", "All time"]].map(([value, label]) => <Link key={value} className={range === value ? "active" : ""} href={rangeHref(value)}>{label}</Link>)}</nav>
    {reportLimited && <div className="notice" role="status">This report is limited to the newest {REPORT_TASK_LIMIT.toLocaleString()} tasks for performance. Select a shorter period to see a complete result.</div>}
    {hasPermission(subject, "WORKSPACE_MANAGE") && <WeeklyManagementSummary summary={weeklySummary} />}
    <section className="manager-kpis"><article className={report.overloaded ? "critical" : "healthy"}><small>Overloaded people</small><strong>{report.overloaded}</strong><span>Above {settings.overloadThreshold}% capacity</span></article><article className={report.risks.length ? "warning" : "healthy"}><small>At-risk tasks</small><strong>{report.risks.length}</strong><span>Actionable risk signals</span></article><article className={report.blocked ? "critical" : "healthy"}><small>Blocked</small><strong>{report.blocked}</strong><span>Waiting for intervention</span></article><article className={report.unassigned ? "warning" : "healthy"}><small>Unassigned</small><strong>{report.unassigned}</strong><span>Open tasks without an owner</span></article><article className={report.unestimated ? "warning" : "healthy"}><small>Unestimated</small><strong>{report.unestimated}</strong><span>Invisible workload</span></article></section>
    <section className="manager-workload-section"><header><div><span className="eyebrow">CAPACITY FORECAST</span><h2>Four-week workload</h2><p>Effort due in each week compared with each member’s available capacity.</p></div>{hasPermission(subject, "WORKSPACE_MANAGE") && <WorkloadSettingsForm workspaceId={workspace.id} initial={settings} />}</header><div className="workload-heatmap-wrap"><table className="workload-heatmap"><thead><tr><th>Team member</th>{report.weeks.map((week) => <th key={week.label}>{week.label}</th>)}<th>Open work</th></tr></thead><tbody>{report.workload.map((item) => <tr key={item.user.id}><th><strong>{item.user.name || item.user.email}</strong><small>{minutesToHours(item.capacityMinutes)}h weekly capacity</small></th>{item.weekly.map((week) => <td key={week.label} className={week.utilization > settings.overloadThreshold ? "load-over" : week.utilization >= 80 ? "load-high" : week.utilization >= 40 ? "load-balanced" : "load-light"}><strong>{week.utilization >= 999 ? "200%+" : `${week.utilization}%`}</strong><small>{minutesToHours(week.effortMinutes)}h / {minutesToHours(week.capacityMinutes)}h</small></td>)}<td><strong>{minutesToHours(item.remainingMinutes)}h</strong><small>{item.open} tasks</small></td></tr>)}</tbody></table></div></section>
    <section className="manager-grid"><article className="risk-queue"><header><div><span className="eyebrow">NEEDS A DECISION</span><h2>At-risk work</h2></div><Link href={`/board?workspace=${encodeURIComponent(slug)}`}>Open task board</Link></header>{report.risks.slice(0, 8).map(({ task, reasons }) => <div className="risk-item" key={task.id}><div><strong>{task.title || "Untitled task"}</strong><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority.toLowerCase()}</span></div><p>{reasons.join(" · ")}</p><small>{task.dueAt ? `Due ${new Date(task.dueAt).toLocaleDateString()}` : "No due date"}</small></div>)}{report.risks.length === 0 && <p className="report-empty">No current workload risks. The team is in good shape.</p>}</article><article className="manager-recommendations"><span className="eyebrow">RECOMMENDED ACTIONS</span><h2>Workload opportunities</h2>{report.workload.filter((item) => item.utilization > settings.overloadThreshold).map((item) => { const available = report.workload.find((candidate) => candidate.utilization < 70); return <p key={item.user.id}><strong>Rebalance {item.user.name || item.user.email}</strong><span>{item.utilization}% utilized{available ? `; review work that could move to ${available.user.name || available.user.email} (${available.utilization}%).` : "; move work to a later date or add capacity."}</span></p>; })}{report.unestimated > 0 && <p><strong>Estimate {report.unestimated} open tasks</strong><span>Unestimated work is excluded from utilization and can hide overload.</span></p>}{report.blocked > 0 && <p><strong>Resolve {report.blocked} blockers</strong><span>Start with the oldest blocked and highest-priority work.</span></p>}{report.overloaded === 0 && report.unestimated === 0 && report.blocked === 0 && <p><strong>No immediate action</strong><span>Capacity and delivery signals are currently healthy.</span></p>}</article></section>
    <section className="completion-date-filter" aria-labelledby="completion-date-filter-title"><div><span className="eyebrow">OUTPUT REPORT DATE</span><h2 id="completion-date-filter-title">Completion date</h2><p>Filters Product &amp; image reports by when tasks were completed. Leave both dates blank to use the Task health period; the end date is included.</p></div><form method="get" action="/reports"><input type="hidden" name="workspace" value={slug} /><input type="hidden" name="range" value={range} /><label><span>Start date</span><input type="date" name="completedFrom" defaultValue={completedFrom} max={completedTo || today} /></label><label><span>End date</span><input type="date" name="completedTo" defaultValue={completedTo} min={completedFrom || undefined} max={today} /></label><button className="primary-button small">Apply dates</button>{hasCustomCompletionRange && <Link className="ghost-button completion-clear" href={`/reports?workspace=${encodeURIComponent(slug)}&range=${range}`}>Clear</Link>}</form>{"error" in customCompletionRange && <p className="date-filter-error" role="alert">{customCompletionRange.error}</p>}</section>
    <section className="report-kpis"><article><small>Total tasks</small><strong>{report.total}</strong></article><article><small>Completion rate</small><strong>{report.completionRate}%</strong></article><article><small>Overdue</small><strong>{report.overdue}</strong></article><article><small>Due in 7 days</small><strong>{report.dueSoon}</strong></article><article><small>Estimate accuracy</small><strong>{report.estimateAccuracy}%</strong></article></section>
    <section className="count-report-section" aria-labelledby="count-report-title"><header><div><span className="eyebrow">OUTPUT ACTIVITY</span><h2 id="count-report-title">Product &amp; image counts</h2><p>Totals from tasks completed in the selected completion-date period. Unchecked task metrics are excluded.</p></div><span className="count-report-coverage"><strong>{counts.reportingTasks}</strong> {counts.reportingTasks === 1 ? "task" : "tasks"} reporting</span></header><div className="count-report-grid">{countCards.map(([label, value, kind]) => <article className={kind} key={label}><small>{label}</small><strong>{value.toLocaleString()}</strong></article>)}</div><div className="count-report-totals"><span>Total product activity <strong>{counts.totalProducts.toLocaleString()}</strong></span><span>Total image activity <strong>{counts.totalImages.toLocaleString()}</strong></span></div>{counts.reportingTasks === 0 && <p className="count-report-empty">No completed tasks have recorded product or image counts in this date range.</p>}</section>
    <section className="output-report workload-report" aria-labelledby="output-report-title"><header><div><h2 id="output-report-title">Output by team member</h2><p>Compare reported product and image work while keeping each activity type visible.</p></div><span className="output-total"><small>Total output</small><strong>{counts.totalOutput.toLocaleString()}</strong></span></header><div className="report-table-wrap"><table className="output-report-table"><thead><tr><th rowSpan={2}>Team member</th><th rowSpan={2}>Tasks reporting</th><th className="product-group" colSpan={2}>Products</th><th className="image-group" colSpan={2}>Images</th><th rowSpan={2}>Total output</th></tr><tr><th>Updated</th><th>New</th><th>Updated</th><th>New</th></tr></thead><tbody>{report.outputByMember.map((item) => <tr key={item.user.id}><td><strong>{item.user.name || item.user.email}</strong>{item.user.email && <small>{item.user.email}</small>}</td><td><span className="reporting-count">{item.reportingTasks}</span></td><td>{item.updatedProducts.toLocaleString()}</td><td>{item.newProducts.toLocaleString()}</td><td>{item.updatedImages.toLocaleString()}</td><td>{item.newImages.toLocaleString()}</td><td className="output-value">{item.totalOutput.toLocaleString()}</td></tr>)}</tbody><tfoot><tr><th>Workspace total</th><td>{counts.reportingTasks}</td><td>{counts.updatedProducts.toLocaleString()}</td><td>{counts.newProducts.toLocaleString()}</td><td>{counts.updatedImages.toLocaleString()}</td><td>{counts.newImages.toLocaleString()}</td><td>{counts.totalOutput.toLocaleString()}</td></tr></tfoot></table></div></section>
    <section className="report-panels"><article><h2>Status breakdown</h2>{report.statuses.map((item) => <div className="metric-bar" key={item.status}><span>{statusLabels[item.status]}</span><div><i style={{ width: `${(item.count / maxStatus) * 100}%` }} /></div><strong>{item.count}</strong></div>)}</article><article><h2>Priority breakdown</h2>{report.priorities.map((item) => <div className="metric-bar priority-bar" key={item.priority}><span>{item.priority[0] + item.priority.slice(1).toLowerCase()}</span><div><i style={{ width: `${(item.count / maxPriority) * 100}%` }} /></div><strong>{item.count}</strong></div>)}</article></section>
    <section className="flow-report"><header><div><span className="eyebrow">DELIVERY FLOW</span><h2>Eight-week throughput</h2><p>Completed work and average cycle time reveal whether delivery is becoming more predictable.</p></div></header><div className="flow-chart">{report.flowWeeks.map((week) => <div className="flow-week" key={week.label}><div className="flow-bar-wrap"><span className="flow-bar" style={{ height: `${Math.max(6, week.completed * 16)}px` }} title={`${week.completed} completed`} /></div><strong>{week.completed}</strong><small>{week.label}</small><em>{week.averageCycleDays ? `${week.averageCycleDays}d cycle` : "—"}</em></div>)}</div></section>
    <section className="workload-report member-drilldown"><h2>Team member detail</h2><div className="report-table-wrap"><table><thead><tr><th>Team member</th><th>Capacity</th><th>Remaining</th><th>Utilization</th><th>Open</th><th>Blocked</th><th>Overdue</th><th>Unestimated</th></tr></thead><tbody>{report.workload.map((item) => <tr key={item.user.id}><td><strong>{item.user.name || item.user.email}</strong><small>{item.user.email}</small></td><td>{minutesToHours(item.capacityMinutes)}h</td><td>{minutesToHours(item.remainingMinutes)}h</td><td><span className={`utilization-pill ${item.utilization > settings.overloadThreshold ? "over" : item.utilization >= 80 ? "high" : "ok"}`}>{item.utilization >= 999 ? "200%+" : `${item.utilization}%`}</span></td><td>{item.open}</td><td className={item.blocked ? "risk" : ""}>{item.blocked}</td><td className={item.overdue ? "risk" : ""}>{item.overdue}</td><td className={item.unestimated ? "risk" : ""}>{item.unestimated}</td></tr>)}</tbody></table></div></section>
  </AppShell>;
}
