"use client";
import { useMemo, useState, type FormEvent } from "react";

type EmailStatus = "UNTRIAGED" | "CONVERTED" | "DISMISSED";
type InboxEmail = { id: string; subject: string; senderAddress: string; senderName: string | null; toAddresses: string[]; ccAddresses: string[]; snippet: string | null; receivedAt: string | Date; status: EmailStatus; connector: { id: string; mailboxAddress: string; displayName: string | null }; task: { id: string; title: string } | null; handledBy: { name: string | null; email: string } | null };
type Rule = { id?: string; action: "INCLUDE" | "EXCLUDE"; field: "SENDER" | "RECIPIENT"; matchType: "EXACT" | "DOMAIN"; value: string; enabled: boolean };
type Connector = { id: string; mailboxAddress: string; displayName: string | null; enabled: boolean; syncIntervalMinutes: number; lastHeartbeatAt: string | Date | null; lastSyncAt: string | Date | null; lastError: string | null; filters: Rule[]; _count: { emails: number } };
type Member = { role: string; user: { id: string; name: string | null; email: string } };
type Task = { id: string; title: string; status: string };
type Setup = { connectorId: string; connectorToken: string; taskflowBaseUrl: string | null; requiresPublicUrl: boolean };
const tabs: Array<[EmailStatus, string]> = [["UNTRIAGED", "Untriaged"], ["CONVERTED", "Converted"], ["DISMISSED", "Dismissed"]];
const intervals = [1, 5, 10, 15, 30, 60];
function person(member: Member) { return member.user.name || member.user.email; }
function formatDate(value: string | Date | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never"; }
function recipientSummary(email: InboxEmail) { return email.toAddresses.length ? email.toAddresses.join(", ") : email.connector.mailboxAddress; }
function isPublicHttpsUrl(value: string) { try { const url = new URL(value); return url.protocol === "https:" && !/^(localhost|127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/i.test(url.hostname); } catch { return false; } }

export function EmailInboxClient({ initialEmails, initialConnectors, members, tasks, workspaceId, workspaceSlug, canManage, canTriage, currentUserId }: { initialEmails: InboxEmail[]; initialConnectors: Connector[]; members: Member[]; tasks: Task[]; workspaceId: string; workspaceSlug: string; canManage: boolean; canTriage: boolean; currentUserId: string }) {
  const [emails, setEmails] = useState(initialEmails); const [connectors, setConnectors] = useState(initialConnectors); const [tab, setTab] = useState<EmailStatus>("UNTRIAGED"); const [view, setView] = useState<"inbox" | "connections">("inbox"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<InboxEmail | null>(null); const [linking, setLinking] = useState<string | null>(null); const [editingConnector, setEditingConnector] = useState<string | null>(null); const [setup, setSetup] = useState<Setup | null>(null); const [setupBaseUrl, setSetupBaseUrl] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const visible = useMemo(() => emails.filter((email) => email.status === tab && `${email.subject} ${email.senderAddress} ${email.snippet || ""}`.toLowerCase().includes(query.toLowerCase())), [emails, tab, query]);
  const counts = useMemo(() => Object.fromEntries(tabs.map(([status]) => [status, emails.filter((email) => email.status === status).length])), [emails]);
  async function json(url: string, options?: RequestInit) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "The request could not be completed"); return data; }
  function showSetup(next: Setup) { setSetup(next); setSetupBaseUrl(next.taskflowBaseUrl || ""); }
  async function setEmailStatus(email: InboxEmail, status: "UNTRIAGED" | "DISMISSED") { try { const updated = await json(`/api/emails/${email.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); setEmails((items) => items.map((item) => item.id === email.id ? { ...item, ...updated } : item)); setNotice(status === "DISMISSED" ? "Email dismissed." : "Email restored to the inbox."); } catch (error) { setNotice((error as Error).message); } }
  async function convert(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setBusy(true); try { const form = new FormData(event.currentTarget); const task = await json(`/api/emails/${selected.id}/convert`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: form.get("title"), description: form.get("description") || null, priority: form.get("priority"), status: form.get("status"), assigneeUserId: form.get("assigneeUserId") || null, dueAt: form.get("dueAt") ? new Date(String(form.get("dueAt"))).toISOString() : null }) }); setEmails((items) => items.map((item) => item.id === selected.id ? { ...item, status: "CONVERTED", task } : item)); setSelected(null); setNotice(`Task created: ${task.title}`); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function link(email: InboxEmail, taskId: string) { if (!taskId) return; setBusy(true); try { const updated = await json(`/api/emails/${email.id}/link`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ taskId }) }); setEmails((items) => items.map((item) => item.id === email.id ? { ...item, status: "CONVERTED", task: updated.task } : item)); setLinking(null); setNotice(`Email linked to ${updated.task.title}.`); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function createConnector(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); try { const form = new FormData(event.currentTarget); const created = await json(`/api/workspaces/${workspaceId}/email-connectors`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mailboxAddress: form.get("mailboxAddress"), displayName: form.get("displayName") || null, syncIntervalMinutes: Number(form.get("syncIntervalMinutes")) }) }); setConnectors((items) => [...items, { ...created, filters: [], _count: { emails: 0 } }]); showSetup(created.setup); event.currentTarget.reset(); setNotice("Connection created. Complete the one-time Apps Script setup."); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function patchConnector(connector: Connector, data: Record<string, unknown>) { setBusy(true); try { const updated = await json(`/api/workspaces/${workspaceId}/email-connectors/${connector.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); setConnectors((items) => items.map((item) => item.id === connector.id ? updated : item)); setNotice("Email connection updated."); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function saveRules(event: FormEvent<HTMLFormElement>, connector: Connector) { event.preventDefault(); const form = new FormData(event.currentTarget); const count = Number(form.get("ruleCount")); const filters: Rule[] = []; for (let index = 0; index < count; index++) { const value = String(form.get(`value-${index}`) || "").trim(); if (value) filters.push({ action: form.get(`action-${index}`) as Rule["action"], field: form.get(`field-${index}`) as Rule["field"], matchType: form.get(`matchType-${index}`) as Rule["matchType"], value, enabled: form.get(`enabled-${index}`) === "on" }); } await patchConnector(connector, { filters }); setEditingConnector(null); }
  async function syncNow(connector: Connector) { try { await json(`/api/workspaces/${workspaceId}/email-connectors/${connector.id}/sync-now`, { method: "POST" }); setNotice("Sync requested. The connector will pick it up within one minute."); } catch (error) { setNotice((error as Error).message); } }
  async function generateSetup(connector: Connector) { setBusy(true); try { const result = await json(`/api/workspaces/${workspaceId}/email-connectors/${connector.id}/setup`, { method: "POST" }); showSetup(result.setup); setNotice("New setup values generated. The previous connector token is now invalid."); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function removeConnector(connector: Connector) { if (!confirm(`Disconnect ${connector.mailboxAddress}? Its captured emails will also be removed.`)) return; try { const response = await fetch(`/api/workspaces/${workspaceId}/email-connectors/${connector.id}`, { method: "DELETE" }); if (!response.ok) throw new Error((await response.json()).error); setConnectors((items) => items.filter((item) => item.id !== connector.id)); setEmails((items) => items.filter((item) => item.connector.id !== connector.id)); } catch (error) { setNotice((error as Error).message); } }
  return <>
    <header className="page-header email-page-header"><div><span className="eyebrow">TURN INBOX SIGNALS INTO WORK</span><h1>Email Inbox</h1><p>Review lightweight Gmail metadata, then create or link the right task.</p></div>{canManage && <div className="email-view-switch"><button className={view === "inbox" ? "active" : ""} onClick={() => setView("inbox")}>Inbox</button><button className={view === "connections" ? "active" : ""} onClick={() => setView("connections")}>Connections</button></div>}</header>
    {notice && <div className="notice email-notice" role="status">{notice}<button onClick={() => setNotice("")} aria-label="Dismiss message">×</button></div>}
    {view === "connections" && connectors.length > 0 && <section className="setup-recovery"><div><strong>Need to finish or repair Google setup?</strong><span>Generate fresh one-time Script Property values for the mailbox you are configuring.</span></div>{connectors.map((connector) => <button key={connector.id} disabled={busy} onClick={() => generateSetup(connector)}>Setup {connector.displayName || connector.mailboxAddress}</button>)}</section>}
    {view === "inbox" ? <>
      <section className="email-toolbar"><nav aria-label="Email status">{tabs.map(([status, label]) => <button key={status} className={tab === status ? "active" : ""} onClick={() => setTab(status)}>{label}<span>{counts[status]}</span></button>)}</nav><input type="search" placeholder="Search subject, sender or preview..." value={query} onChange={(event) => setQuery(event.target.value)} /></section>
      <section className="email-list">{visible.map((email) => <article key={email.id} className="email-row"><div className="email-sender-avatar">{(email.senderName || email.senderAddress)[0].toUpperCase()}</div><div className="email-summary"><div><strong>{email.subject}</strong><time>{formatDate(email.receivedAt)}</time></div><p><b>{email.senderName || email.senderAddress}</b> <span>&lt;{email.senderAddress}&gt;</span> → {recipientSummary(email)}</p>{email.snippet && <small>{email.snippet}</small>}<div className="email-source"><span>{email.connector.displayName || email.connector.mailboxAddress}</span>{email.task && <a href={`/board?workspace=${encodeURIComponent(workspaceSlug)}`}>Task: {email.task.title}</a>}</div></div>{canTriage && <div className="email-actions">{email.status === "UNTRIAGED" ? <><button className="primary-button small" onClick={() => setSelected(email)}>Create task</button><button onClick={() => setLinking(linking === email.id ? null : email.id)}>Link task</button><button onClick={() => setEmailStatus(email, "DISMISSED")}>Dismiss</button></> : email.status === "DISMISSED" ? <button onClick={() => setEmailStatus(email, "UNTRIAGED")}>Restore</button> : null}{linking === email.id && <select autoFocus defaultValue="" disabled={busy} onChange={(event) => link(email, event.target.value)}><option value="" disabled>Select task...</option>{tasks.map((task) => <option value={task.id} key={task.id}>{task.title} · {task.status.replaceAll("_", " ")}</option>)}</select>}</div>}</article>)}{visible.length === 0 && <div className="empty-state"><span>✉</span><h2>No emails here</h2><p>{tab === "UNTRIAGED" ? "New matching emails will appear after a connector syncs." : "There are no emails in this category."}</p></div>}</section>
    </> : <section className="connection-page"><form className="connection-create" onSubmit={createConnector}><div><span className="eyebrow">NEW MAILBOX</span><h2>Connect a Gmail address</h2><p>Only metadata matching your rules is stored. Attachments and full bodies are never requested.</p></div><label>Mailbox email<input name="mailboxAddress" type="email" placeholder="catalog@company.com" required /></label><label>Display name<input name="displayName" placeholder="Catalog inbox" maxLength={80} /></label><label>Sync interval<select name="syncIntervalMinutes" defaultValue="5">{intervals.map((value) => <option key={value} value={value}>{value === 60 ? "Every hour" : `Every ${value} minute${value === 1 ? "" : "s"}`}</option>)}</select></label><button className="primary-button" disabled={busy}>Create connection</button></form><div className="connector-grid">{connectors.map((connector) => <article className="connector-card" key={connector.id}><header><div><span className={`connection-status ${!connector.enabled ? "paused" : connector.lastError ? "error" : connector.lastHeartbeatAt ? "healthy" : "waiting"}`} /> <strong>{connector.displayName || connector.mailboxAddress}</strong><small>{connector.mailboxAddress}</small></div><label className="switch"><input type="checkbox" checked={connector.enabled} onChange={(event) => patchConnector(connector, { enabled: event.target.checked })} /><span />{connector.enabled ? "Active" : "Paused"}</label></header><dl><div><dt>Last sync</dt><dd>{formatDate(connector.lastSyncAt)}</dd></div><div><dt>Last heartbeat</dt><dd>{formatDate(connector.lastHeartbeatAt)}</dd></div><div><dt>Captured</dt><dd>{connector._count.emails}</dd></div><div><dt>Rules</dt><dd>{connector.filters.length}</dd></div></dl>{connector.lastError && <p className="connection-error">{connector.lastError}</p>}<label className="interval-control">Schedule<select value={connector.syncIntervalMinutes} onChange={(event) => patchConnector(connector, { syncIntervalMinutes: Number(event.target.value) })}>{intervals.map((value) => <option key={value} value={value}>{value === 60 ? "Hourly" : `${value} min`}</option>)}</select></label><div className="connector-actions"><button onClick={() => syncNow(connector)}>Sync now</button><button onClick={() => setEditingConnector(editingConnector === connector.id ? null : connector.id)}>Filters</button><button className="danger" onClick={() => removeConnector(connector)}>Disconnect</button></div>{editingConnector === connector.id && <RuleEditor connector={connector} onSave={saveRules} onCancel={() => setEditingConnector(null)} />}</article>)}</div></section>}
    {selected && <div className="drawer-backdrop" onClick={() => setSelected(null)}><aside className="email-convert-drawer" role="dialog" aria-modal="true" aria-labelledby="email-convert-title" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={() => setSelected(null)}>×</button><span className="eyebrow">CONVERT EMAIL</span><h2 id="email-convert-title">Create a task</h2><div className="source-preview"><strong>{selected.subject}</strong><span>{selected.senderAddress} · {formatDate(selected.receivedAt)}</span><p>{selected.snippet || "No preview provided by Gmail."}</p></div><form onSubmit={convert} className="detail-form"><label>Task title<input name="title" defaultValue={selected.subject.slice(0, 120)} required maxLength={120} /></label><label>Description<textarea name="description" rows={5} defaultValue={`Email from: ${selected.senderName || selected.senderAddress}\nReceived: ${formatDate(selected.receivedAt)}\n\n${selected.snippet || ""}`} maxLength={2000} /></label><div className="detail-grid"><label>Status<select name="status"><option value="TODO">To do</option><option value="IN_PROGRESS">In progress</option><option value="NO_ACTION_NEEDED">No Action Needed</option></select></label><label>Priority<select name="priority" defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><label>Due date<input name="dueAt" type="datetime-local" /></label></div><label>Assignee<select name="assigneeUserId" defaultValue=""><option value="">Unassigned</option>{members.map((member) => <option key={member.user.id} value={member.user.id}>{person(member)}{member.user.id === currentUserId ? " (me)" : ""}</option>)}</select></label><button className="primary-button" disabled={busy}>{busy ? "Creating..." : "Create task"}</button></form></aside></div>}
    {setup && <div className="drawer-backdrop" onClick={() => setSetup(null)}>
      <aside className="setup-dialog" role="dialog" aria-modal="true" aria-labelledby="setup-title" onClick={(event) => event.stopPropagation()}>
        <button className="drawer-close" onClick={() => setSetup(null)}>×</button>
        <span className="eyebrow">ONE-TIME GOOGLE SETUP</span>
        <h2 id="setup-title">Activate this mailbox</h2>
        {!isPublicHttpsUrl(setupBaseUrl) && <div className="setup-url-warning" role="alert"><strong>A public HTTPS address is required</strong><span>Google Apps Script cannot connect to localhost. Deploy TaskFlow or start a secure public tunnel, then paste its HTTPS origin below.</span></div>}
        <ol>
          <li>Make TaskFlow available at a stable public HTTPS address.</li>
          <li>Open <a href="https://script.google.com/home/projects/create" target="_blank" rel="noreferrer">Google Apps Script</a> while signed into the mailbox.</li>
          <li>Copy the latest <a href="/api/email-connectors/apps-script/code" target="_blank">Code.gs</a> and <a href="/api/email-connectors/apps-script/manifest" target="_blank">appsscript.json</a> into the project.</li>
          <li>Open <b>Project Settings → Script Properties</b>, add the three values below, and save.</li>
          <li>Select <code>configureTaskFlow</code>, click <b>Run</b>, and approve Google&apos;s metadata-only permission.</li>
        </ol>
        <div className="setup-properties">
          <label><strong>TASKFLOW_BASE_URL</strong><input type="url" value={setupBaseUrl} onChange={(event) => setSetupBaseUrl(event.target.value)} placeholder="https://your-taskflow-domain.example" aria-invalid={!isPublicHttpsUrl(setupBaseUrl)} /></label>
          <p><strong>TASKFLOW_CONNECTOR_ID</strong><code>{setup.connectorId}</code></p>
          <p><strong>TASKFLOW_CONNECTOR_TOKEN</strong><code>{setup.connectorToken}</code></p>
        </div>
        <p className="security-note">The token is shown once and is stored only in Apps Script Properties. Because it appeared in your screenshot, generate new setup values before the final connection.</p>
        <button className="primary-button" disabled={!isPublicHttpsUrl(setupBaseUrl)} onClick={() => navigator.clipboard.writeText(`TASKFLOW_BASE_URL=${new URL(setupBaseUrl).origin}\nTASKFLOW_CONNECTOR_ID=${setup.connectorId}\nTASKFLOW_CONNECTOR_TOKEN=${setup.connectorToken}`)}>Copy property values</button>
      </aside>
    </div>}
  </>;
}

function RuleEditor({ connector, onSave, onCancel }: { connector: Connector; onSave: (event: FormEvent<HTMLFormElement>, connector: Connector) => void; onCancel: () => void }) {
  const [rules, setRules] = useState<Rule[]>(connector.filters.length ? connector.filters : [{ action: "INCLUDE", field: "RECIPIENT", matchType: "EXACT", value: connector.mailboxAddress, enabled: true }]);
  return <form className="rule-editor" onSubmit={(event) => onSave(event, connector)}><input type="hidden" name="ruleCount" value={rules.length} /><div><strong>Capture rules</strong><small>Exclusions always win. Sender and receiver inclusions must both match.</small></div>{rules.map((rule, index) => <div className="rule-row" key={index}><select name={`action-${index}`} value={rule.action} onChange={(event) => setRules((items) => items.map((item, i) => i === index ? { ...item, action: event.target.value as Rule["action"] } : item))}><option value="INCLUDE">Include</option><option value="EXCLUDE">Exclude</option></select><select name={`field-${index}`} value={rule.field} onChange={(event) => setRules((items) => items.map((item, i) => i === index ? { ...item, field: event.target.value as Rule["field"] } : item))}><option value="SENDER">Sender</option><option value="RECIPIENT">Receiver</option></select><select name={`matchType-${index}`} value={rule.matchType} onChange={(event) => setRules((items) => items.map((item, i) => i === index ? { ...item, matchType: event.target.value as Rule["matchType"] } : item))}><option value="EXACT">Exact email</option><option value="DOMAIN">Domain</option></select><input name={`value-${index}`} value={rule.value} onChange={(event) => setRules((items) => items.map((item, i) => i === index ? { ...item, value: event.target.value } : item))} placeholder={rule.matchType === "DOMAIN" ? "supplier.com" : "person@example.com"} required /><label><input type="checkbox" name={`enabled-${index}`} checked={rule.enabled} onChange={(event) => setRules((items) => items.map((item, i) => i === index ? { ...item, enabled: event.target.checked } : item))} />On</label><button type="button" aria-label="Remove rule" onClick={() => setRules((items) => items.filter((_, i) => i !== index))}>×</button></div>)}<div className="rule-actions"><button type="button" onClick={() => setRules((items) => [...items, { action: "INCLUDE", field: "SENDER", matchType: "EXACT", value: "", enabled: true }])}>+ Add rule</button><span /><button type="button" onClick={onCancel}>Cancel</button><button className="primary-button small">Save rules</button></div></form>;
}
