import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { AppShell } from "@/components/app-shell";
import { NotificationActions } from "@/components/notification-actions";
import { NotificationPreferences } from "@/components/notification-preferences";
import { TelegramConnection } from "@/components/telegram-connection";
import { listUserWorkspaces } from "@/lib/server/authorization";
import { prisma, withDatabaseRetry } from "@/lib/server/prisma";
export default async function NotificationsPage() { const session = await auth(); if (!session?.user?.id) redirect("/login"); const [items, preferences, telegramConnection, workspaces] = await withDatabaseRetry(() => Promise.all([prisma.notification.findMany({ where: { userId: session.user.id }, include: { task: { select: { title: true } }, workspace: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 50 }), prisma.user.findUniqueOrThrow({ where: { id: session.user.id }, select: { emailNotifications: true, taskReminderNotifications: true } }), prisma.telegramConnection.findUnique({ where: { userId: session.user.id }, select: { id: true, username: true, firstName: true, linkedAt: true, lastSeenAt: true, enabled: true } }), listUserWorkspaces(session.user.id)])); const unread = items.filter((item) => !item.readAt).length; return <AppShell active="notifications" userName={session.user.name} workspaces={workspaces}><header className="page-header"><div><span className="eyebrow">STAY IN THE LOOP</span><h1>Notifications</h1><p>Everything that needs your attention, in one place.</p></div><NotificationActions unread={unread} /></header><NotificationPreferences initialEmail={preferences.emailNotifications} initialReminders={preferences.taskReminderNotifications} /><TelegramConnection configured={Boolean(process.env.TELEGRAM_BOT_TOKEN && process.env.TELEGRAM_BOT_USERNAME && process.env.TELEGRAM_WEBHOOK_SECRET)} initialConnection={telegramConnection ? { ...telegramConnection, linkedAt: telegramConnection.linkedAt.toISOString(), lastSeenAt: telegramConnection.lastSeenAt?.toISOString() || null } : null} /><section className="notification-list">{items.length ? items.map((item) => <article className={item.readAt ? "read" : ""} key={item.id}><span className="notification-dot"/><div><strong>{item.message}</strong><p>{item.workspace.name}{item.task ? ` - ${item.task.title}` : ""}</p><small>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(item.createdAt)}</small></div><span className={`delivery ${item.emailStatus.toLowerCase()}`}>{item.emailStatus}</span></article>) : <div className="empty-state"><span>OK</span><h2>All quiet</h2><p>No notifications yet.</p></div>}</section></AppShell>; }
